// Generated by typings
// Source: https://raw.githubusercontent.com/oherman1/typed-node-tree-kill/be35a1c6092d4406b08448c880bcbe9c4b5f43bc/index.d.ts
declare module 'tree-kill' {
/**
 * Kill all processes in the process tree, including the root process.
 */

interface IKill {
   (processId: number, signal?: string, callback?: (err: any) => any): void;
 }

const kill: IKill;

export = kill;
}
